version: '3.8'
services:
  mariadb:
    image: mariadb:10.4
    container_name: arriety_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arriety
    ports:
      - "3308:3306"
    volumes:
      - ./Arriety/arriety.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
